### ISSUE TITLE
Missing README

### ISSUE THREAD

**Issue by fulkast** [tschmidt23/NDTensor#1]
Hey Tanner,

May you elaborate more on this project?

Sincerely,
Frank

**Comment by tschmidt23** [comment]
Hi Frank,

The point of this library is to provide a single template class to represent tensors of arbitrary dimensionality and type either in host (CPU) or device (GPU) memory. So, for example, the same class can represent a vector (D=1), matrix / image (D=2), volume (D=3), or higher-dimensional tensors. It also provides a memory-managed version and a number of helper functions for indexing, interpolation, bounds checks, etc. These functions are written generically such that they are generated in place at compile time given the type and dimensionality of the tensor.

I'm quite busy this week but I'll try to put a README together next week with some example usage.

- Tanner

**Comment by fulkast** [comment]
Hello Tanner,

Thank you for the clarification! I look forward to trying it out.

Frank

**Comment by tschmidt23** [comment]
Closed with e2732fd8d9aed85e1abad6f5515bbd54a76ee306

**Comment by fulkast** [comment]
Thanks Tanner!
